# Working with Numpy

Numpy is the numerical python package, with a lot of mathematical capabilities. Before we can use it, we need to first import the package. We will import it under the name np such that we can afterwards refer to it by this short name.

In [1]:
# your code here
import numpy as np

In the cell below, generate two 2x3 array with all elements equal to 1 - assign one of the arrays to the variable a and the other one to b. Add the two arrays. What do you get?

In [5]:
# your code here
a = np.full((2,3),1)
b = np.full((2,3),1)
print(np.add(a,b))

[[2 2 2]
 [2 2 2]]


Now generate another array c which is a 3x2 array with all elements equal to 1. Are you able to add a and c? Why or why not?

In [6]:
# your code here
c = np.full((3,2),1)
print(np.add(a,c))
# No, arrays with different shapes cannot be operated together.

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Transpose c so that it has the same structure of a (i.e. become a 2x3 array). Assign the transposed array to variable "d". Are you able to add a and d?

In [7]:
# your code here
d = np.transpose(c)
print(np.add(a,d))
# Yes, now it is possible as both `a` and `d` have the same shape (2x3).

[[2 2 2]
 [2 2 2]]


Which combination of arrays are you able to multiply with each other? Why?

In [13]:
# your code here
print(np.multiply(a,c))

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [14]:
print(np.multiply(b,d))

# For multiplication, arrays also need to have the same size.

[[1 1 1]
 [1 1 1]]


Create a list which contains the numbers from 0 to 10. Square the list elementwise using numpy functions.

In [18]:
# your code here
x = np.arange(0,11)
y = np.square(x)
print(y)

[  0   1   4   9  16  25  36  49  64  81 100]


Create a numpy array of size 10x10 which has random numbers between 0 and 100 on the main diagonal and zeros otherwise.

In [30]:
# your code here
import random
a = np.zeros((10, 10), int)
np.fill_diagonal(a,random.choice(range(0,101)))

array([[6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 6, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 6, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 6, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 6]])